### ISSUE TITLE
Would you consider separating each extension into different repos?

### ISSUE THREAD

**Issue by Hexcles** [kgshank/gnome-shell-extensions#7]
It looks a little weird now in terms of the way sources are organized. And it would be much clearer and convenient for others to fork.

Anyway, thanks for your work. I'm using your sound output switcher which really helps me a lot!

**Comment by kgshank** [comment]
Thanks Hexcles for the suggestion. I just created the repo as a place to dump the codes. I will reorganize them into individual repos.

**Comment by kgshank** [comment]
Individual Repositories created for each extension
